import { useState } from "react";
import { Language } from "@/types";

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    guests: "Guest Room",
    global: "Global",
    paradise: "Paradise",
    esmart: "E-Smart",
    esonewworld: "ESOneWorld",
    search: "Search or enter URL...",
    chats: "Chats",
    calls: "Calls",
    media: "Media",
    groups: "Groups",
    communities: "Communities",
    quran: "Holy Quran",
    hadees: "Hadith",
    islamic: "Islamic Series",
    gallery: "Gallery",
    settings: "Settings",
    admin: "Admin Panel",
    about: "About Us",
    welcome: "Welcome to ESOneWorld",
    tagline: "A Global Family Platform",
    login: "Login",
    register: "Register",
    phone: "Phone Number",
    enterOTP: "Enter OTP",
    verify: "Verify",
    send: "Send OTP",
    name: "Your Name",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    language: "Language",
    theme: "Theme",
    notifications: "Notifications",
    privacy: "Privacy Policy",
    disclaimer: "Disclaimer",
    copyright: "Copyright",
    vision: "Our Vision",
    mission: "Our Mission",
    contact: "Contact Us",
    connected: "Connected With Us",
    launcher: "Launcher Theme",
    addMore: "Add More",
    integrations: "Integrations",
    importApp: "Import App",
    loading: "Loading...",
    online: "Online",
    offline: "Last seen recently",
  },
  ur: {
    home: "ہوم",
    guests: "گیسٹ روم",
    global: "گلوبل",
    paradise: "جنت",
    esmart: "ای۔سمارٹ",
    esonewworld: "ای۔ایس۔ون۔ورلڈ",
    search: "تلاش کریں یا URL درج کریں...",
    chats: "چیٹس",
    calls: "کالز",
    media: "میڈیا",
    groups: "گروپس",
    communities: "کمیونٹیز",
    quran: "قرآن پاک",
    hadees: "احادیث",
    islamic: "اسلامی سیریز",
    gallery: "گیلری",
    settings: "ترتیبات",
    admin: "ایڈمن پینل",
    about: "ہمارے بارے میں",
    welcome: "خوش آمدید ESOneWorld",
    tagline: "ایک عالمی خاندانی پلیٹ فارم",
    login: "لاگ ان",
    register: "رجسٹر",
    phone: "فون نمبر",
    enterOTP: "OTP درج کریں",
    verify: "تصدیق کریں",
    send: "OTP بھیجیں",
    name: "آپ کا نام",
    darkMode: "ڈارک موڈ",
    lightMode: "لائٹ موڈ",
    language: "زبان",
    theme: "تھیم",
    notifications: "اطلاعات",
    privacy: "رازداری پالیسی",
    disclaimer: "دستبرداری",
    copyright: "کاپی رائٹ",
    vision: "ہمارا وژن",
    mission: "ہمارا مشن",
    contact: "ہم سے رابطہ",
    connected: "ہم سے جڑیں",
    launcher: "لانچر تھیم",
    addMore: "مزید شامل کریں",
    integrations: "انضمام",
    importApp: "ایپ درآمد کریں",
    loading: "لوڈ ہو رہا ہے...",
    online: "آن لائن",
    offline: "حال ہی میں دیکھا گیا",
  },
  ar: {
    home: "الرئيسية",
    guests: "غرفة الضيوف",
    global: "عالمي",
    paradise: "الجنة",
    esmart: "إي-سمارت",
    esonewworld: "إي إس ون وورلد",
    search: "ابحث أو أدخل URL...",
    chats: "المحادثات",
    calls: "المكالمات",
    media: "الوسائط",
    groups: "المجموعات",
    communities: "المجتمعات",
    quran: "القرآن الكريم",
    hadees: "الأحاديث",
    islamic: "السلسلة الإسلامية",
    gallery: "المعرض",
    settings: "الإعدادات",
    admin: "لوحة الإدارة",
    about: "من نحن",
    welcome: "مرحباً بكم في ESOneWorld",
    tagline: "منصة الأسرة العالمية",
    login: "تسجيل الدخول",
    register: "التسجيل",
    phone: "رقم الهاتف",
    enterOTP: "أدخل OTP",
    verify: "تحقق",
    send: "إرسال OTP",
    name: "اسمك",
    darkMode: "الوضع الداكن",
    lightMode: "الوضع الفاتح",
    language: "اللغة",
    theme: "السمة",
    notifications: "الإشعارات",
    privacy: "سياسة الخصوصية",
    disclaimer: "إخلاء المسؤولية",
    copyright: "حقوق النشر",
    vision: "رؤيتنا",
    mission: "مهمتنا",
    contact: "اتصل بنا",
    connected: "تواصل معنا",
    launcher: "سمة المشغل",
    addMore: "إضافة المزيد",
    integrations: "التكاملات",
    importApp: "استيراد تطبيق",
    loading: "جارٍ التحميل...",
    online: "متصل",
    offline: "شوهد مؤخراً",
  },
};

export function useLanguage() {
  const [lang, setLang] = useState<Language>(() => {
    return (localStorage.getItem("esonewworld-lang") as Language) || "en";
  });

  const t = (key: string): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  const changeLanguage = (l: Language) => {
    setLang(l);
    localStorage.setItem("esonewworld-lang", l);
    document.documentElement.dir = l === "en" ? "ltr" : "rtl";
    document.documentElement.lang = l;
  };

  const dir = lang === "en" ? "ltr" : "rtl";
  const fontClass = lang === "ur" ? "font-urdu" : lang === "ar" ? "font-arabic" : "font-inter";

  return { lang, t, changeLanguage, dir, fontClass };
}
